/**
 * SERP Feasibility Calculator
 *
 * Produces a deterministic 1-10 score from observable SERP evidence.
 * Score is NOT generated by an LLM — it is computed from live SERP data.
 *
 * Score interpretation:
 *   9-10 = Weak results dominate (forums, thin pages) — new sites can rank quickly
 *   7-8  = Moderate competition — quality content can compete in 3-6 months
 *   5-6  = Established authority sites — hard without backlinks
 *   3-4  = Strong brands present — long-term effort required
 *   1-2  = Wikipedia/major brands dominate — near impossible without massive DA
 */

import type { SerpOrganicResult, SerpFeatureData } from "./dataforseo";

export interface SerpEvidenceInput {
    organicResults: SerpOrganicResult[];
    featureTypes: string[];
}

export interface SerpFeasibilityResult {
    /** 1-10 feasibility score. Higher = easier to rank. */
    score: number;
    /** Human-readable explanation of how the score was calculated. */
    explanation: string;
    /** Individual signal contributions for transparency. */
    signals: SerpSignal[];
}

export interface SerpSignal {
    signal: string;
    impact: number; // positive = good for you, negative = bad for you
    detail: string;
}

// Domains considered "mega-authority" that are nearly impossible to displace
const MEGA_AUTHORITY_DOMAINS = new Set([
    "wikipedia.org",
    "reddit.com",
    "youtube.com",
    "amazon.com",
    "quora.com",
    "medium.com",
    "linkedin.com",
    "facebook.com",
    "twitter.com",
    "x.com",
    "forbes.com",
    "healthline.com",
    "webmd.com",
    "mayoclinic.org",
    "nih.gov",
    "cdc.gov",
    "gov.uk",
    "nytimes.com",
    "bbc.com",
    "bbc.co.uk",
]);

// Forum/community domains — positive signal (often weak, displaceable)
const FORUM_DOMAINS = new Set([
    "reddit.com",
    "quora.com",
    "stackexchange.com",
    "stackoverflow.com",
    "answers.yahoo.com",
    "community.spiceworks.com",
]);

const LOW_BACKLINK_THRESHOLD = 50;
const MODERATE_BACKLINK_THRESHOLD = 500;

/**
 * Calculates SERP feasibility from live organic SERP data.
 * All scoring is deterministic — no AI involved.
 */
export function calculateSerpFeasibility(evidence: SerpEvidenceInput): SerpFeasibilityResult {
    const { organicResults, featureTypes } = evidence;
    const signals: SerpSignal[] = [];
    let score = 5; // neutral starting point

    if (organicResults.length === 0) {
        return {
            score: 5,
            explanation: "No SERP data available — using neutral score.",
            signals: [],
        };
    }

    // ── Positive signals (easier to rank) ────────────────────────────────────

    // Weak backlink profiles in top results
    const resultsWithBacklinkData = organicResults.filter((r) => r.backlinks !== undefined);
    if (resultsWithBacklinkData.length > 0) {
        const weakResults = resultsWithBacklinkData.filter(
            (r) => (r.backlinks ?? 0) < LOW_BACKLINK_THRESHOLD
        ).length;
        const weakRatio = weakResults / resultsWithBacklinkData.length;
        const boost = Math.round(weakRatio * 3);
        if (boost > 0) {
            score += boost;
            signals.push({
                signal: "Weak backlink profiles",
                impact: boost,
                detail: `${weakResults}/${resultsWithBacklinkData.length} top results have <${LOW_BACKLINK_THRESHOLD} referring domains`,
            });
        }
    }

    // Forum/Reddit results in top 10 — these are displaceable
    const forumResults = organicResults.filter((r) => FORUM_DOMAINS.has(r.domain)).length;
    if (forumResults > 0) {
        const boost = Math.min(2, forumResults);
        score += boost;
        signals.push({
            signal: "Forum/community results",
            impact: boost,
            detail: `${forumResults} forum results in top ${organicResults.length} — displaceable with quality content`,
        });
    }

    // Diverse domain landscape (no single domain dominates)
    const domains = organicResults.map((r) => r.domain);
    const uniqueDomains = new Set(domains).size;
    if (uniqueDomains >= Math.floor(organicResults.length * 0.8)) {
        score += 1;
        signals.push({
            signal: "Diverse domains",
            impact: 1,
            detail: `${uniqueDomains} unique domains in results — no single site dominates`,
        });
    }

    // ── Negative signals (harder to rank) ────────────────────────────────────

    // SERP features reduce organic click-through opportunity
    if (featureTypes.includes("featured_snippet")) {
        score -= 1;
        signals.push({
            signal: "Featured snippet present",
            impact: -1,
            detail: "Featured snippet reduces CTR for organic results below it",
        });
    }

    if (featureTypes.includes("local_pack")) {
        score -= 1;
        signals.push({
            signal: "Local pack present",
            impact: -1,
            detail: "Local pack takes up screen space, reducing organic visibility",
        });
    }

    if (featureTypes.includes("shopping")) {
        score -= 1;
        signals.push({
            signal: "Shopping results present",
            impact: -1,
            detail: "Shopping carousel displaces organic listings",
        });
    }

    // Mega-authority domains that are near-impossible to displace
    const megaResults = organicResults.filter((r) => MEGA_AUTHORITY_DOMAINS.has(r.domain));
    if (megaResults.length >= 3) {
        score -= 2;
        signals.push({
            signal: "Mega-authority dominance",
            impact: -2,
            detail: `${megaResults.length} mega-authority domains (e.g. ${megaResults.slice(0, 2).map((r) => r.domain).join(", ")})`,
        });
    } else if (megaResults.length >= 1) {
        score -= 1;
        signals.push({
            signal: "Authority domains present",
            impact: -1,
            detail: `${megaResults.length} high-authority domain(s): ${megaResults.map((r) => r.domain).join(", ")}`,
        });
    }

    // Strong backlink profiles in most top results
    if (resultsWithBacklinkData.length > 0) {
        const strongResults = resultsWithBacklinkData.filter(
            (r) => (r.backlinks ?? 0) > MODERATE_BACKLINK_THRESHOLD
        ).length;
        if (strongResults >= 3) {
            score -= 1;
            signals.push({
                signal: "Strong competitor backlink profiles",
                impact: -1,
                detail: `${strongResults} results have >${MODERATE_BACKLINK_THRESHOLD}+ referring domains`,
            });
        }
    }

    const finalScore = Math.max(1, Math.min(10, score));

    const explanation = buildExplanation(finalScore, signals);

    return { score: finalScore, explanation, signals };
}

function buildExplanation(score: number, signals: SerpSignal[]): string {
    const positive = signals.filter((s) => s.impact > 0);
    const negative = signals.filter((s) => s.impact < 0);

    const parts: string[] = [];
    if (positive.length > 0) {
        parts.push(`Opportunity signals: ${positive.map((s) => s.signal.toLowerCase()).join(", ")}.`);
    }
    if (negative.length > 0) {
        parts.push(`Challenges: ${negative.map((s) => s.signal.toLowerCase()).join(", ")}.`);
    }

    const verdict =
        score >= 8 ? "High opportunity — new content can rank." :
        score >= 6 ? "Moderate opportunity — quality content can compete." :
        score >= 4 ? "Challenging — strong existing competitors." :
        "Difficult — established authority dominates.";

    return [verdict, ...parts].join(" ");
}

/**
 * Convenience wrapper that takes a raw SerpFeatureData object
 * (as returned by getSerpData) and runs feasibility calculation.
 */
export function feasibilityFromSerpData(serpData: SerpFeatureData): SerpFeasibilityResult {
    return calculateSerpFeasibility({
        organicResults: serpData.organicResults,
        featureTypes: serpData.featureTypes,
    });
}
