import { logger } from "@/lib/logger";

export interface EmailDispatchPayload {
    recipientEmail: string;
    clientSiteName: string;
    agencyName: string;
    customDomain: string;
    pdfBufferLength: number;
}

export interface EmailDispatchResult {
    success: boolean;
    messageId: string;
    deliveredAt: Date;
    error?: string;
}

export async function dispatchWhiteLabelExecutiveDigest(
    payload: EmailDispatchPayload
): Promise<EmailDispatchResult> {
    const deliveredAt = new Date();

    const resendKey = process.env.RESEND_API_KEY;
    const fromDomain = process.env.RESEND_FROM_DOMAIN;

    if (!resendKey || !fromDomain) {
        logger.warn("[EmailDispatcher] White-label digest NOT sent — RESEND_API_KEY or RESEND_FROM_DOMAIN not configured", {
            recipient: payload.recipientEmail,
            agency: payload.agencyName,
        });

        return {
            success: false,
            messageId: "",
            deliveredAt,
            error: "Email service not configured. Set RESEND_API_KEY and RESEND_FROM_DOMAIN to enable white-label digest delivery.",
        };
    }

    try {
        const { Resend } = await import("resend");
        const resend = new Resend(resendKey);

        const appUrl = process.env.NEXTAUTH_URL ?? process.env.NEXT_PUBLIC_SITE_URL ?? "https://optiaiseo.online";
        const fromAddress = payload.customDomain
            ? `${payload.agencyName} <noreply@${payload.customDomain}>`
            : `${payload.agencyName} via OptiAISEO <noreply@${fromDomain}>`;

        const result = await resend.emails.send({
            from: fromAddress,
            to: payload.recipientEmail,
            subject: `${payload.clientSiteName} — Executive SEO Report from ${payload.agencyName}`,
            html: `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#09090b;font-family:'Inter',Arial,sans-serif;color:#f4f4f5;">
  <div style="max-width:520px;margin:0 auto;padding:32px 24px;">
    <div style="background:#10b981;padding:24px;text-align:center;border-radius:12px 12px 0 0;">
      <div style="font-size:11px;font-weight:700;letter-spacing:2px;color:rgba(255,255,255,0.8);text-transform:uppercase;">${payload.agencyName}</div>
      <h1 style="font-size:20px;font-weight:800;margin:8px 0 0;color:#fff;">Executive SEO Report</h1>
    </div>
    <div style="background:#111;padding:24px;border:1px solid #1f2937;border-top:none;border-radius:0 0 12px 12px;">
      <p style="font-size:14px;color:#a1a1aa;">Your executive SEO report for <strong style="color:#f4f4f5;">${payload.clientSiteName}</strong> is attached as a PDF.</p>
      <p style="font-size:12px;color:#6b7280;margin-top:16px;">Report generated by ${payload.agencyName}</p>
    </div>
    <div style="padding:16px;text-align:center;">
      <p style="font-size:11px;color:#52525b;">This is a one-time report delivery. <a href="${appUrl}/dashboard/settings?tab=notifications" style="color:#4ade80;text-decoration:none;">Manage notification preferences</a></p>
    </div>
  </div>
</body>
</html>`,
            text: [
                `Executive SEO Report — ${payload.clientSiteName}`,
                ``,
                `Your executive SEO report is attached as a PDF (${Math.round(payload.pdfBufferLength / 1024)} KB).`,
                ``,
                `Report generated by ${payload.agencyName}`,
                ``,
                `Manage notification preferences: ${appUrl}/dashboard/settings?tab=notifications`,
            ].join("\n"),
        });

        const messageId = (result?.data as { id?: string })?.id ?? `msg-${Date.now()}`;

        logger.info("[EmailDispatcher] Dispatched white-label client PDF digest", {
            recipient: payload.recipientEmail,
            agency: payload.agencyName,
            messageId,
        });

        return {
            success: true,
            messageId,
            deliveredAt,
        };
    } catch (err: unknown) {
        logger.error("[EmailDispatcher] Failed to dispatch email digest", {
            recipient: payload.recipientEmail,
            error: (err as Error)?.message || String(err),
        });

        return {
            success: false,
            messageId: "",
            deliveredAt,
            error: (err as Error)?.message || String(err),
        };
    }
}

