/**
 * src/lib/serp-gap/plan-generator.ts
 *
 * Implementation Plan Generator
 *
 * Takes a GapReport and produces a structured, week-by-week content
 * upgrade plan that the client can execute (or Aria can act on).
 *
 * The plan is generated by Gemini and structured as a typed object
 * so the UI can render it richly.
 */

import { callGeminiJson } from "@/lib/gemini/client";
import { logger } from "@/lib/logger";
import type { GapReport, ContentGap } from "./analyser";

export interface ContentSection {
    section: string;
    rationale: string;
    guidanceNotes: string;
    targetWordCount: number;
    competitorExamples: string[];
}

export interface AuthorityStep {
    step: number;
    action: string;
    detail: string;
    estimatedWeeks: string;
}

// ─── Types ───────────────────────────────────────────────────────────────────

export interface PlanTask {
    id: string;
    week: 1 | 2 | 3 | 4;
    priority: "critical" | "high" | "medium" | "low";
    category: "content" | "technical" | "schema" | "ux" | "eeat";
    title: string;
    description: string;
    /** What the client does manually */
    manualSteps: string[];
    /** Whether Aria / auto-PR can action this */
    ariaCanAutomate: boolean;
    ariaAction?: string;
    estimatedTimeMinutes: number;
    /** Expected ranking outcome if completed */
    expectedOutcome: string;
    sourceGap: string;
}

export interface ImplementationPlan {
    keyword: string;
    clientUrl: string;
    clientCurrentPosition: number;
    estimatedPositionGain: string;
    estimatedTimeToResult: string;
    executiveSummary: string;
    topPriority: string;
    formatInsight: string;
    rankingTimelineNote: string | null;
    tasks: PlanTask[];
    week1Focus: string;
    week2Focus: string;
    week3Focus: string;
    week4Focus: string;
    contentBlueprint: ContentSection[];
    authorityRoadmap: AuthorityStep[];
    generatedAt: string;
}

// ─── Prompt builder ───────────────────────────────────────────────────────────

function buildPlanPrompt(report: GapReport): string {
    const gapSummary = report.gaps
        .slice(0, 8)
        .map(
            (g, i) =>
                `${i + 1}. [${g.gap.toUpperCase()}] ${g.dimension}\n   Client: ${g.clientValue} | Competitors avg: ${g.topCompetitorAvg}\n   Impact: ${g.impact}\n   Fix: ${g.recommendation}`
        )
        .join("\n\n");

    const competitorH2s = report.topResults
        .filter((r) => r.fetchedOk)
        .slice(0, 3)
        .map((r) => `${r.url} (${r.wordCount} words): ${r.h2s.slice(0, 6).join(" | ")}`)
        .join("\n");

    const missingTopics = report.competitorTopicMap
        .slice(0, 10)
        .map((t) => `- "${t.topic}" (${t.mentionCount}/${report.topResults.filter(r => r.fetchedOk).length} competitors)`)
        .join("\n");

    return `You are a senior SEO strategist creating a precise 4-week content upgrade plan.

CONTEXT:
- Keyword: "${report.keyword}"
- Client page: ${report.clientUrl}
- Current position: ${report.clientPosition} (page ${Math.ceil(report.clientPosition / 10)})
- SERP format: ${report.serpFormat} (${report.serpHasAiOverview ? "has AI Overview" : "no AI Overview"}, ${report.serpHasFeaturedSnippet ? "has featured snippet" : "no featured snippet"}, ${report.serpHasPaa ? "has PAA" : "no PAA"})
- Client word count: ${report.clientSignals.wordCount} | Competitor average: ${report.topCompetitorAvgWordCount}
- Client has FAQ: ${report.clientSignals.hasFaqSection} | Has FAQ schema: ${report.clientSignals.hasFaqSchema}
- Client has video: ${report.clientSignals.hasVideo} | Has ToC: ${report.clientSignals.hasTableOfContents}
${report.rankingTimelineNote ? `- AUTHORITY NOTE: ${report.rankingTimelineNote}` : ""}

CONTENT GAPS (already computed):
${gapSummary}

TOP COMPETITOR H2 STRUCTURES:
${competitorH2s}

MISSING TOPICS (H2s competitors cover that client doesn't):
${missingTopics || "None identified"}

Generate a realistic, actionable 4-week implementation plan. Each task must be concrete and specific to this keyword and page — no generic advice.

For ariaCanAutomate: set to true ONLY for schema injection, meta tag updates, technical fixes. Content writing is always false.

Return ONLY a valid JSON object with this exact structure:
{
  "executiveSummary": "2-3 sentences explaining why this page isn't ranking and the core fix strategy",
  "topPriority": "The single most impactful change — one sentence",
  "formatInsight": "One sentence about whether the client is using the right content format vs what the SERP rewards",
  "estimatedPositionGain": "e.g. 'Move from position ${report.clientPosition} to top 5' — be realistic",
  "estimatedTimeToResult": "e.g. '4-8 weeks after implementation'",
  "week1Focus": "One sentence summarising week 1 theme",
  "week2Focus": "One sentence summarising week 2 theme",
  "week3Focus": "One sentence summarising week 3 theme",
  "week4Focus": "One sentence summarising week 4 theme",
  "tasks": [
    {
      "id": "task-1",
      "week": 1,
      "priority": "critical",
      "category": "content",
      "title": "Short task title",
      "description": "Specific description of exactly what to do for this keyword/page",
      "manualSteps": ["Step 1...", "Step 2...", "Step 3..."],
      "ariaCanAutomate": false,
      "ariaAction": null,
      "estimatedTimeMinutes": 90,
      "expectedOutcome": "What this fixes and estimated impact",
      "sourceGap": "Content depth (word count)"
    }
  ],
  "contentBlueprint": [
    {
      "section": "H2 heading to add, e.g. 'How to Choose the Right Tool'",
      "rationale": "Why this section matters — which competitors have it and what ranking signal it sends",
      "guidanceNotes": "Exactly what to write in 3-4 sentences: key points to cover, tone, real-world examples to include",
      "targetWordCount": 300,
      "competitorExamples": ["https://competitor.com/page"]
    }
  ],
  "authorityRoadmap": [
    {
      "step": 1,
      "action": "Short action label",
      "detail": "Specific, concrete instructions for this step — who to contact, what to offer, how to pitch",
      "estimatedWeeks": "Weeks 1-2"
    }
  ]
}

Rules:
- Generate 8-12 tasks total across 4 weeks
- contentBlueprint: generate one entry per missing topic from the MISSING TOPICS list above (up to 8)
- authorityRoadmap: generate 4-6 concrete link-building steps relevant to this specific keyword/niche
- Week 1: Critical and high-priority quick wins
- Week 2: Content depth and structure improvements
- Week 3: E-E-A-T, citations, schema
- Week 4: Monitoring, internal links, promotion
- No markdown, no backticks, return raw JSON only`;
}

// ─── Main export ──────────────────────────────────────────────────────────────

export async function generateImplementationPlan(
    report: GapReport
): Promise<ImplementationPlan | null> {
    if (!process.env.GEMINI_API_KEY) {
        logger.warn("[PlanGenerator] GEMINI_API_KEY not set");
        return null;
    }

    logger.info("[PlanGenerator] Generating plan", {
        keyword: report.keyword,
        gaps: report.gaps.length,
        clientPosition: report.clientPosition,
    });

    try {
        const prompt = buildPlanPrompt(report);
        const raw = await callGeminiJson<Omit<ImplementationPlan, "keyword" | "clientUrl" | "clientCurrentPosition" | "generatedAt">>(
            prompt,
            { maxOutputTokens: 4096, temperature: 0.2 }
        );

        if (!raw || !raw.tasks?.length) {
            logger.warn("[PlanGenerator] Gemini returned empty plan", { keyword: report.keyword });
            return buildFallbackPlan(report);
        }

        return {
            ...raw,
            keyword: report.keyword,
            clientUrl: report.clientUrl,
            clientCurrentPosition: report.clientPosition,
            rankingTimelineNote: report.rankingTimelineNote ?? null,
            contentBlueprint: raw.contentBlueprint ?? buildFallbackBlueprint(report),
            authorityRoadmap: raw.authorityRoadmap ?? buildFallbackAuthorityRoadmap(report.keyword),
            generatedAt: new Date().toISOString(),
        };
    } catch (err) {
        logger.error("[PlanGenerator] Plan generation failed", { keyword: report.keyword, err });
        return buildFallbackPlan(report);
    }
}


function buildFallbackBlueprint(report: GapReport): ContentSection[] {
    return report.competitorTopicMap.slice(0, 8).map((t) => ({
        section: t.topic,
        rationale: `${t.mentionCount} of your top competitors cover this topic. Adding it closes a visible content gap that contributes to their ranking advantage.`,
        guidanceNotes: `Write 200-400 words that directly address the implied question in "${t.topic}". Open with a one-sentence direct answer, then expand with 2-3 supporting points and a concrete example. Keep sentences under 20 words.`,
        targetWordCount: 300,
        competitorExamples: t.competitorUrls.slice(0, 3),
    }));
}

function buildFallbackAuthorityRoadmap(keyword: string): AuthorityStep[] {
    return [
        { step: 1, action: "Link Intersect Audit", detail: `Use Ahrefs or Moz Link Intersect to find domains linking to 2+ competitors for "${keyword}" but not you. Export the top 20 by DR.`, estimatedWeeks: "Week 1" },
        { step: 2, action: "Broken Link Outreach", detail: "For each intersect domain, check for broken outbound links using Check My Links. Offer your page as a replacement with a personalised one-line email.", estimatedWeeks: "Weeks 1-2" },
        { step: 3, action: "Resource Page Pitches", detail: `Search: intitle:"resources" "${keyword}". Find pages listing competitor content and pitch yours as more comprehensive.`, estimatedWeeks: "Weeks 2-3" },
        { step: 4, action: "Digital PR - Original Data", detail: `Create one data asset relevant to "${keyword}" (survey or aggregated stats). Pitch to 10-15 niche publications. 2-3 DR 40+ pickups will move the needle.`, estimatedWeeks: "Weeks 3-4" },
        { step: 5, action: "Internal Authority Boost", detail: "Find your 3 highest-authority pages. Add a contextual link from each to this page using partial-match anchor text. Internal PageRank flows immediately.", estimatedWeeks: "Week 1" },
    ];
}

function buildFallbackPlan(report: GapReport): ImplementationPlan {
    const tasks: PlanTask[] = report.gaps.slice(0, 8).map((gap: ContentGap, i: number) => ({
        id: `task-${i + 1}`,
        week: (Math.min(Math.floor(i / 2) + 1, 4)) as 1 | 2 | 3 | 4,
        priority: gap.gap,
        category: gap.dimension.toLowerCase().includes("schema") ? "schema"
            : gap.dimension.toLowerCase().includes("content") || gap.dimension.toLowerCase().includes("word") ? "content"
                : gap.dimension.toLowerCase().includes("author") ? "eeat"
                    : "technical",
        title: gap.dimension,
        description: gap.impact,
        manualSteps: gap.recommendation.split("\n").filter(Boolean),
        ariaCanAutomate: gap.dimension.toLowerCase().includes("schema"),
        ariaAction: gap.dimension.toLowerCase().includes("schema") ? `Add ${gap.dimension} to the page` : undefined,
        estimatedTimeMinutes: gap.gap === "critical" ? 180 : gap.gap === "high" ? 90 : 45,
        expectedOutcome: `Closes the ${gap.dimension} gap vs. top competitors`,
        sourceGap: gap.dimension,
    }));

    return {
        keyword: report.keyword,
        clientUrl: report.clientUrl,
        clientCurrentPosition: report.clientPosition,
        estimatedPositionGain: `Move from position ${report.clientPosition} into top 10`,
        estimatedTimeToResult: "4-8 weeks after implementation",
        executiveSummary: `Your page for "${report.keyword}" is ranking at position ${report.clientPosition} with ${report.gaps.length} identified gaps vs. the top-ranking content. The primary issues are: ${report.gaps.slice(0, 3).map((g) => g.dimension).join(", ")}.`,
        topPriority: report.gaps[0]?.recommendation.split("\n")[0] ?? "Audit and expand page content depth.",
        formatInsight: `The SERP rewards ${report.serpFormat} format. Ensure your content matches this format.`,
        rankingTimelineNote: report.rankingTimelineNote ?? null,
        week1Focus: "Fix critical structural and schema gaps",
        week2Focus: "Expand content depth and heading structure",
        week3Focus: "Strengthen E-E-A-T signals and citations",
        week4Focus: "Internal linking, monitoring, and promotion",
        tasks,
        contentBlueprint: buildFallbackBlueprint(report),
        authorityRoadmap: buildFallbackAuthorityRoadmap(report.keyword),
        generatedAt: new Date().toISOString(),
    };
}
