import { notFound } from "next/navigation";
import type { Metadata } from "next";
import Link from "next/link";
import { prisma } from "@/lib/prisma";

interface Props {
    params: Promise<{ token: string }>;
}

const TOKEN_RE = /^[0-9a-f]{64}$/;
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://optiaiseo.online").replace(/\/$/, "");

async function getShareData(token: string) {
    if (!TOKEN_RE.test(token)) return null;

    const share = await prisma.auditShare.findUnique({
        where: { token },
        select: {
            expiresAt: true,
            audit: {
                select: {
                    categoryScores: true,
                    issueList: true,
                    lcp: true,
                    cls: true,
                    inp: true,
                    runTimestamp: true,
                    site: { select: { domain: true } },
                },
            },
        },
    });

    if (!share || share.expiresAt < new Date()) return null;

    await prisma.auditShare.update({
        where: { token },
        data: { viewCount: { increment: 1 } },
    });

    return share;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { token } = await params;
    const share = await getShareData(token);
    if (!share) return { title: "Audit Report | OptiAISEO" };

    return {
        title: `SEO Audit — ${share.audit.site.domain} | OptiAISEO`,
        description: `Full SEO audit report for ${share.audit.site.domain} generated by OptiAISEO.`,
        robots: { index: false, follow: false },
        openGraph: {
            title: `SEO Audit — ${share.audit.site.domain}`,
            description: `View the full SEO audit results for ${share.audit.site.domain}.`,
            images: [{ url: `${SITE_URL}/og-image.png`, width: 1200, height: 630 }],
        },
    };
}

function scoreColor(s: number) {
    if (s >= 75) return "text-emerald-400 bg-emerald-500/10 border-emerald-500/30";
    if (s >= 50) return "text-yellow-400 bg-yellow-500/10 border-yellow-500/30";
    return "text-red-400 bg-red-500/10 border-red-500/30";
}

function scoreGradient(s: number) {
    if (s >= 75) return "from-emerald-500/8";
    if (s >= 50) return "from-yellow-500/8";
    return "from-red-500/8";
}

type RawIssue = {
    severity?: string;
    type?: string;
    category?: string;
    title?: string;
    itemId?: string;
    description?: string;
    finding?: string;
    fixSuggestion?: string;
    recommendation?: string;
};

function normalizeIssues(raw: unknown): RawIssue[] {
    if (Array.isArray(raw)) return raw as RawIssue[];
    if (raw && typeof raw === "object") {
        const obj = raw as Record<string, unknown>;
        if (Array.isArray(obj.recommendations)) {
            return (obj.recommendations as Record<string, unknown>[]).map((r) => ({
                category: r.categoryId as string,
                severity: r.priority === "High" ? "error" : "warning",
                title: r.itemId as string,
                description: r.finding as string,
                fixSuggestion: r.recommendation as string,
            }));
        }
        if (Array.isArray(obj.issues)) return obj.issues as RawIssue[];
    }
    return [];
}

export default async function SharePage({ params }: Props) {
    const { token } = await params;
    const share = await getShareData(token);

    if (!share) notFound();

    const { audit } = share;
    const scores = (audit.categoryScores ?? {}) as Record<string, number>;
    const issues = normalizeIssues(audit.issueList);
    const errors = issues.filter((i) => (i.severity ?? i.type) === "error");
    const warnings = issues.filter((i) => (i.severity ?? i.type) === "warning");
    const passes = issues.filter((i) => !["error", "warning"].includes((i.severity ?? i.type) ?? ""));

    const grouped = issues.reduce<Record<string, RawIssue[]>>((acc, issue) => {
        const cat = (issue.category ?? "general").toLowerCase().replace(/\s+/g, "-");
        (acc[cat] ??= []).push(issue);
        return acc;
    }, {});

    const daysLeft = Math.ceil((share.expiresAt.getTime() - Date.now()) / 86_400_000);

    return (
        <div className="min-h-screen bg-background">
            <nav className="w-full border-b border-border bg-background/95 backdrop-blur-sm sticky top-0 z-50">
                <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
                    <Link href="/" className="flex items-center gap-2" aria-label="OptiAISEO home">
                        <div className="w-7 h-7 rounded-md bg-foreground flex items-center justify-center shrink-0">
                            <span className="font-black text-background text-[10px] tracking-tight">Opti</span>
                        </div>
                        <span className="font-bold text-sm tracking-tight">OptiAISEO</span>
                    </Link>
                    <div className="flex items-center gap-3">
                        <span className="text-xs text-muted-foreground hidden sm:block">
                            Link expires in {daysLeft} day{daysLeft !== 1 ? "s" : ""}
                        </span>
                        <Link
                            href="/signup"
                            className="text-xs font-semibold bg-foreground text-background px-3 py-1.5 rounded-full hover:opacity-90 transition-all"
                        >
                            Audit your site free →
                        </Link>
                    </div>
                </div>
            </nav>

            <main className="max-w-5xl mx-auto px-6 py-12 flex flex-col gap-6">
                <div>
                    <p className="text-xs text-muted-foreground mb-1">
                        SEO Audit Report · {new Date(audit.runTimestamp).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}
                    </p>
                    <h1 className="text-2xl font-bold tracking-tight">{audit.site.domain}</h1>
                </div>

                <div className="p-3 rounded-xl border border-brand/20 bg-brand/5 text-xs text-brand font-medium">
                    This is a read-only shared audit report. It does not contain any personal or account information.
                </div>

                {Object.keys(scores).length > 0 && (
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                        {Object.entries(scores).map(([cat, score]) => (
                            <div key={cat} className={`card-surface p-4 bg-gradient-to-b ${scoreGradient(score)} to-transparent`}>
                                <p className={`text-3xl font-bold ${score >= 75 ? "text-emerald-400" : score >= 50 ? "text-yellow-400" : "text-red-400"}`}>
                                    {score}
                                </p>
                                <p className="text-xs text-muted-foreground capitalize mt-1">{cat}</p>
                            </div>
                        ))}
                        {audit.lcp != null && (
                            <div className="card-surface p-4">
                                <p className="text-3xl font-bold text-blue-400">{Number(audit.lcp).toFixed(1)}s</p>
                                <p className="text-xs text-muted-foreground mt-1">LCP</p>
                            </div>
                        )}
                        {audit.cls != null && (
                            <div className="card-surface p-4">
                                <p className="text-3xl font-bold text-purple-400">{Number(audit.cls).toFixed(3)}</p>
                                <p className="text-xs text-muted-foreground mt-1">CLS</p>
                            </div>
                        )}
                        {audit.inp != null && (
                            <div className="card-surface p-4">
                                <p className="text-3xl font-bold text-pink-400">{Number(audit.inp)}ms</p>
                                <p className="text-xs text-muted-foreground mt-1">INP</p>
                            </div>
                        )}
                    </div>
                )}

                <div className="grid grid-cols-3 gap-4">
                    <div className="card-surface p-4 border-l-4 border-l-red-500/60">
                        <p className="text-2xl font-bold text-red-400">{errors.length}</p>
                        <p className="text-sm text-muted-foreground">Errors</p>
                    </div>
                    <div className="card-surface p-4 border-l-4 border-l-yellow-500/60">
                        <p className="text-2xl font-bold text-yellow-400">{warnings.length}</p>
                        <p className="text-sm text-muted-foreground">Warnings</p>
                    </div>
                    <div className="card-surface p-4 border-l-4 border-l-blue-500/60">
                        <p className="text-2xl font-bold text-blue-400">{passes.length}</p>
                        <p className="text-sm text-muted-foreground">Opportunities</p>
                    </div>
                </div>

                {Object.keys(grouped).length > 0 && (
                    <div className="space-y-3">
                        <h2 className="font-semibold text-lg">Issues ({issues.length})</h2>
                        {Object.entries(grouped).map(([cat, catIssues]) => {
                            const errCount = catIssues.filter((i) => (i.severity ?? i.type) === "error").length;
                            const warnCount = catIssues.filter((i) => (i.severity ?? i.type) === "warning").length;
                            return (
                                <details key={cat} open={errCount > 0} className="card-surface overflow-hidden group">
                                    <summary className="flex items-center justify-between gap-3 p-4 cursor-pointer hover:bg-card transition-colors list-none">
                                        <div className="flex items-center gap-3">
                                            <span className="font-semibold text-sm capitalize">{cat.replace(/-/g, " ")}</span>
                                            <span className="text-xs text-muted-foreground">{catIssues.length} issue{catIssues.length !== 1 ? "s" : ""}</span>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            {errCount > 0 && <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-red-500/10 text-red-400 border border-red-500/20">{errCount} error{errCount !== 1 ? "s" : ""}</span>}
                                            {warnCount > 0 && <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-yellow-500/10 text-yellow-400 border border-yellow-500/20">{warnCount} warning{warnCount !== 1 ? "s" : ""}</span>}
                                            <svg className="w-4 h-4 text-muted-foreground transition-transform group-open:rotate-180" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                                        </div>
                                    </summary>
                                    <div className="border-t border-border divide-y divide-border">
                                        {catIssues.map((issue, i) => {
                                            const sev = (issue.severity ?? issue.type ?? "info").toLowerCase();
                                            const isError = sev === "error";
                                            const isWarn = sev === "warning";
                                            return (
                                                <div key={i} className="p-4 flex items-start gap-3">
                                                    <span className={`mt-0.5 w-2 h-2 rounded-full shrink-0 ${isError ? "bg-red-400" : isWarn ? "bg-yellow-400" : "bg-blue-400"}`} />
                                                    <div className="flex-1 min-w-0">
                                                        <p className="text-sm font-semibold capitalize">{(issue.title ?? issue.itemId ?? "Issue").replace(/-/g, " ")}</p>
                                                        {(issue.description ?? issue.finding) && (
                                                            <p className="text-xs text-muted-foreground mt-1">{issue.description ?? issue.finding}</p>
                                                        )}
                                                        {(issue.fixSuggestion ?? issue.recommendation) && (
                                                            <p className="text-xs text-brand mt-1 font-medium">Fix: {issue.fixSuggestion ?? issue.recommendation}</p>
                                                        )}
                                                    </div>
                                                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border whitespace-nowrap ${isError ? "bg-red-500/10 text-red-400 border-red-500/20" : isWarn ? "bg-yellow-500/10 text-yellow-400 border-yellow-500/20" : "bg-blue-500/10 text-blue-400 border-blue-500/20"}`}>
                                                        {isError ? "Error" : isWarn ? "Warning" : "Info"}
                                                    </span>
                                                </div>
                                            );
                                        })}
                                    </div>
                                </details>
                            );
                        })}
                    </div>
                )}

                <div className="bg-foreground text-background rounded-2xl p-8 text-center mt-4">
                    <p className="text-xs font-semibold uppercase tracking-widest text-background/50 mb-2">Powered by OptiAISEO</p>
                    <h2 className="text-xl font-bold mb-2">Fix these issues automatically</h2>
                    <p className="text-sm text-background/70 mb-6 max-w-md mx-auto">
                        OptiAISEO detects issues, generates GitHub pull requests to fix them, and tracks your AI visibility across ChatGPT and Perplexity.
                    </p>
                    <Link
                        href="/signup"
                        className="inline-flex items-center gap-2 bg-brand text-white font-bold px-6 py-3 rounded-full hover:opacity-90 transition-all text-sm"
                    >
                        Audit your site free — no card needed →
                    </Link>
                </div>

                <p className="text-center text-xs text-muted-foreground pb-4">
                    This shared report expires on {share.expiresAt.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}
                </p>
            </main>
        </div>
    );
}
