import prisma from "@/lib/prisma";
import { notFound } from "next/navigation";
import { Metadata } from "next";

export const revalidate = 86400; // Cache for 24 hours

export async function generateMetadata(
  props: { params: Promise<{ slug: string }> }
): Promise<Metadata> {
  const params = await props.params;
  const slug = params.slug;

  return {
    title: `Best ${slug.replace(/-/g, " ")} | Market Comparison`,
    description: `Compare the top ${slug.replace(/-/g, " ")}. Generated by our Market Intelligence Engine.`,
  };
}

export default async function MarketComparisonPage(
  props: { params: Promise<{ slug: string }> }
) {
  const params = await props.params;
  const slug = params.slug;

  // Very naive mapping: we'd ideally lookup a slug table, but here we just find a category that matches
  const subcategory = slug.split("-vs-")[0]?.replace(/-/g, " ") || slug.replace(/-/g, " ");
  
  // Find the market category that best matches this slug
  const category = await prisma.marketCategory.findFirst({
    where: {
      subcategory: {
        contains: subcategory,
        mode: "insensitive"
      }
    },
    include: {
      competitors: {
        orderBy: { score: "desc" },
        take: 10,
      }
    }
  });

  if (!category || category.competitors.length === 0) {
    notFound();
  }

  return (
    <div className="max-w-4xl mx-auto py-24 px-6">
      <div className="text-center mb-16">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-foreground mb-6 capitalize">
          Best {category.subcategory} in {category.geo === "Global" ? "the World" : category.geo}
        </h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          We analyzed the market and scored the top providers based on footprint, service match, and market authority.
        </p>
      </div>

      <div className="space-y-8">
        {category.competitors.map((comp, index) => (
          <div key={comp.id} className="bg-card border rounded-xl p-8 flex flex-col md:flex-row items-center md:items-start gap-8 shadow-sm">
            <div className="flex-shrink-0 flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 text-primary font-bold text-2xl">
              #{index + 1}
            </div>
            <div className="flex-grow text-center md:text-left">
              <h2 className="text-2xl font-bold mb-2">{comp.name || comp.domain}</h2>
              <a href={`https://${comp.domain}`} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline text-sm font-medium mb-4 block">
                {comp.domain}
              </a>
              <div className="flex flex-wrap items-center justify-center md:justify-start gap-4">
                <div className="bg-secondary px-3 py-1 rounded-full text-sm font-medium">
                  Score: <span className="text-foreground">{comp.score}/10</span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
      
      <div className="mt-16 bg-muted/50 rounded-xl p-8 text-center border">
        <h3 className="text-lg font-semibold mb-2">How we rank</h3>
        <p className="text-muted-foreground text-sm max-w-2xl mx-auto">
          Our Autonomous Market Intelligence Engine constantly crawls lists, directories, and SERPs to find the true market leaders in every niche. Ranks are based on frequency of mentions, geographical relevance, and website service quality.
        </p>
      </div>
    </div>
  );
}
