ALTER TABLE "SeoFixProposal" ADD COLUMN "proposalBaseCommitSha" TEXT;
ALTER TABLE "SeoFixProposal" ADD COLUMN "proposalTargetBlobSha" TEXT;
ALTER TABLE "SeoFixProposal" ADD COLUMN "prNumber" INTEGER;
ALTER TABLE "SeoFixProposal" ADD COLUMN "mergeCommitSha" TEXT;
ALTER TABLE "SeoFixProposal" ADD COLUMN "deploymentId" TEXT;
ALTER TABLE "SeoFixProposal" ADD COLUMN "deploymentCommitSha" TEXT;
ALTER TABLE "SeoFixProposal" ADD COLUMN "deploymentStatus" TEXT NOT NULL DEFAULT 'NOT_DEPLOYED';
ALTER TABLE "SeoFixProposal" ADD COLUMN "verificationStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "SeoFixProposal" ADD COLUMN "verificationUrl" TEXT;
ALTER TABLE "SeoFixProposal" ADD COLUMN "verificationCriteria" JSONB;
ALTER TABLE "SeoFixProposal" ADD COLUMN "verificationDetails" JSONB;
ALTER TABLE "MutationEffect" ADD COLUMN "externalMetadata" JSONB;
ALTER TABLE "MutationEffect" ADD COLUMN "verificationStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "MutationEffect" ADD COLUMN "verificationDetails" JSONB;
ALTER TABLE "MutationEffect" ADD COLUMN "verifiedAt" TIMESTAMP(3);
CREATE TABLE "MutationVerification" ("id" TEXT NOT NULL PRIMARY KEY, "operationId" TEXT NOT NULL, "proposalId" TEXT, "siteId" TEXT NOT NULL, "verificationType" TEXT NOT NULL, "status" TEXT NOT NULL, "targetUrl" TEXT, "criteria" JSONB NOT NULL, "expectedState" JSONB, "observedState" JSONB, "evidence" JSONB, "attempt" INTEGER NOT NULL DEFAULT 1, "checkedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MutationVerification_operationId_fkey" FOREIGN KEY ("operationId") REFERENCES "MutationOperation"("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "MutationVerification_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX "MutationVerification_operationId_checkedAt_idx" ON "MutationVerification"("operationId","checkedAt");
CREATE INDEX "MutationVerification_siteId_status_idx" ON "MutationVerification"("siteId","status");
CREATE INDEX "MutationVerification_proposalId_checkedAt_idx" ON "MutationVerification"("proposalId","checkedAt");